DPDK/grout

- modules/infra/datapath/drop.c
- modules/infra/datapath/eth_output.c
- modules/ip/datapath/icmp_output.c
- modules/ipip/datapath_out.c
rte_pktmbuf_prepend returns null pointer when there is no available headroom.
Drop and count these packets.
> infra: add drop counter "no_headroom"

- modules/ip/datapath/gr_ip4_datapath.h
- modules/ip/datapath/ip_forward.c
- modules/ip/datapath/ip_forward_ttl_exceeded.c
- modules/ip/datapath/ip_input.c
- modules/ip/datapath/meson.build
Instead of dropping silently the packet, forge and send back an ICMP message "Time To live exceeded".
> ip: send an icmp message when TTL is expired

- api/gr_net_types.h
- cli/ecoli.c
- modules/infra/cli/port.c
- modules/infra/cli/vlan.c
- modules/infra/control/port.c
- modules/ip/cli/address.c
- modules/ip/cli/nexthop.c
- modules/ip/cli/route.c
- modules/ip/control/nexthop.c
This makes lines shorter and everyone is happy.
> net: remove gr_ prefix in frequently used functions

- .github/workflows/ci.yml
- README.md
- devtools/check-patches
Fix the following errors in the lint job:
devtools/check-patches: line 50: jq: command not found
devtools/check-patches: line 50: test: =: unary operator expected
> ci: add missing dependencies

- modules/infra/datapath/control_input.c
- modules/infra/datapath/eth_input.c
- modules/ip/datapath/gr_ip4_datapath.h
- modules/ip/datapath/ip_local.c
- modules/ip/datapath/ip_output.c
- modules/ipip/datapath_out.c
Rename node_name to next_node to make it more explicit.
Log the requested operation before actually calling gr_node_attach_parent so that is easier to debug in case of error.
Also update ip_output_add_tunnel to take a node name instead of an edge id.
> graph: sanitize dynamic node attach to parent

- modules/infra/datapath/control_input.c
- modules/infra/datapath/eth_input.c
- modules/infra/datapath/gr_control_input.h
- modules/ip/datapath/arp_output_request.c
- modules/ip/datapath/ip_local.c
- modules/ip/datapath/ip_output.c
Ensure we don't register two handlers for the same ether type, ip proto, tunnel output interface type or control input type.
To avoid storing information about other modules (IP/ARP) into the infra module, change `gr_control_input_register_handler` to automatically return the next available `control_input_t` value. That function cannot fail and will `ABORT()` if the available values are exhausted.
Fixes: 94a69675b5cb ("graph: sanitize dynamic node attach to parent")
> graph: add duplicate checks for all dynamic nodes

- api/gr_net_types.h
- modules/ip/control/address.c
- modules/ip/control/gr_ip4_control.h
- modules/ip/control/nexthop.c
- modules/ip/control/route.c
On iface deletion, delete assoticated routes.
specify module destructor priorities to ensure
resources are not freed when accessing them.
> ip: clean resources on iface deletion

- modules/infra/datapath/control_input.c
Use correct initialiser for the control input ring.
Fixes: a610da9bdaa9a955a6cb2a85c09ff7eaa1412c78
> infra: fix control_input ring

- api/gr_net_types.h
Byte order needs to be taken into account.
> api: make IP4_ADDR_SPLIT work on big endian architectures

- modules/infra/control/iface.c
Fix null ptr access
I messed up when rebasing/rewriting code, and pushed the wrong patch, introducing a null ptr access when we quit grout.
Fixes: 8beb4d93a61a ("infra: destroy ports after logical interfaces")
> infra: fix null ptr access

- modules/infra/control/gr_iface.h
- modules/infra/control/iface.c
- modules/infra/control/vlan.c
Physical port shouldn't be removed when a vlan interface depends on it.
> iface: prevent port removal when subinterface exists

- modules/ip/control/address.c
- modules/ip/control/gr_ip4_control.h
- modules/ip/datapath/arp_input.c
- modules/ip/datapath/arp_output_request.c
- modules/ip/datapath/ip_forward_error.c
In the datapath, we often need to get the correct IP address on an interface in order to reply or transmit a packet. Rename ip4_addr_get_default to ip4_addr_get_preferred which takes an additional destination IP address as argument. It will return the first address assigned to the interface that is in the same subnet.
If no address is found in that subnet, use the first address by default.
Rename struct iface_addresses to struct hoplist, the structure will be reused in order to support multiple next hops associated with a route prefix.
In a future commit, the next hops will need to be reordered so that the first address is the best default.
> ip: add function to get preferred iface address

- subprojects/dpdk.wrap
- subprojects/packagefiles/dpdk/buildtools-cmdline-fix-meson-error-when-used-as-a-su.patch
Some patches were integrated upstream. Remove them from grout. One fix is required in order to make subprojects work.
> dpdk: rebase on v24.07

- main/dpdk.c
- main/main.c
- main/meson.build
- main/sd_notify.c
- main/sd_notify.h
- main/worker.h
In order to ease running grout as a systemd notify service, implement a standalone version of sd_notify(3). No need to require libsystemd.so.
Link: https://www.freedesktop.org/software/systemd/man/devel/sd_notify.html#Standalone%20Implementations
> main: implement systemd notify

- main/dpdk.c
- main/main.c
By default, DPDK log functions print both to stderr *and* syslog. This is not only unnecessary but also when running as a systemd service, it produces duplicated log lines.
When JOURNAL_STREAM is set in the environment, it indicates that grout has been started by systemd and its stderr is connected to the journal. If that is the case, log using syslog. Otherwise print on stderr prefixing the message with the textual value of the log level.
> main: restrict logging to syslog when running under systemd

- main/dpdk.c
- main/dpdk.h
- main/main.c
- main/signals.c
- modules/infra/control/meson.build
- modules/infra/control/worker.c
- modules/infra/control/worker_test.c
- modules/infra/datapath/main_loop.c
- modules/ip6/control/route.c
- smoke/_init.sh
When using tuned CPU partitioning, the default CPU affinity of processes are often restricted to a set of housekeeping cores. We want the control plane threads to run in these CPUs. However, we also want the data path threads NOT to run on these CPUs, but instead pin them on the previously isolated cores.
Remove the restriction of worker_rxq_assign() cpu_id to be part of the current process CPU affinity. Instead use a pthread attribute to specify the desired affinity based on cpu_id and pass that to pthread_create(). That way, if the cpu_id cannot be used (either because it is invalid or referencing to an offline CPU), pthread_create() will return an appropriate error code that can be returned to the caller. Since this call can now fail, delay the removal of the rxq from the source worker …
> worker: allow starting threads outside of current process affinity

- main/main.c
- meson.build
- modules/infra/api/graph.c
- modules/infra/control/gr_worker.h
- modules/infra/control/graph.c
- modules/infra/control/port.c
- modules/infra/control/worker_test.c
- modules/infra/datapath/main_loop.c
The link status behind eth ports may change at any moment. The only way to get reliable information about the link status and speed is to rely on driver notifications via the link status check interrupt thread (enabled by default in DPDK).
Configure all ports with intr_conf.lsc=1 if supported by the driver. If not supported, the link status and speed will not be updated automatically.
Register an LSC ethdev callback which only serves as a proxy to trigger a libevent callback. That way, the link status information is checked and updated from the main lcore only. libevent needs to be initialized with pthread support to allow other threads to trigger events.
> port: use interrupt thread to monitor link status and speed

- cli/main.c
- docs/grcli.1.scd
- docs/grout.8.scd
- main/main.c
Add -V, --version flags to both grout and grcli. When these flags are specified, print the program version and exit. Update the man pages and usage help accordingly.
> main: add flags to display version

- modules/infra/datapath/eth_input.c
- modules/infra/datapath/trace.c
When the NIC is able to strip the vlan tag, the vlan id is available in the mbuf metadata. Use that information to display the vlan header even if it was stripped from the packet buffer.
> trace: display stripped vlans

- modules/infra/control/iface.c
The name is checked for duplicates on `set interface` but not when creating a new interface. Return an explicit error when trying to create an interface with a name that is already taken.
Fixes: a188078583cf ("infra: replace port with interface abstraction")
> iface: forbid duplicate names on creation

- modules/infra/control/gr_iface.h
- modules/infra/control/iface.c
- modules/infra/control/vlan.c
Allow vlan interfaces to ask their parent port to allow certain multicast ethernet addresses related to their IPv6 addresses.
> vlan: implement multicast ethernet filtering

- CONTRIBUTING.md
- GNUmakefile
Try to explain the requirements with as much detail as possible. Allow two different contribution channels: GitHub pull requests and email.
> docs: add contributing guide

- meson.build
- modules/ip/control/address.c
- modules/ip/control/nexthop.c
- modules/ip6/control/address.c
- modules/ip6/control/nexthop.c
nit picking: First arg of calloc argument should specify number of elements, later size of each element.
> calloc: fix order parameter

- main/api.c
- main/api.h
- main/main.c
- main/meson.build
The main.c file contains both command line parsing, the main() function *and* libevent stuff for managing the API socket. This is too many purposes for a single file.
Move the API socket handling in a separate file. Adjust stuff accordingly.
> main: move libevent api callbacks to separate file

- modules/infra/control/iface.c
When an interface name is already taken, we return an error but the iface pointer is set the already existing interface. Before returning from iface_create, that pointer is freed without removing the interface from the system.
When listing interface or accessing anything after that causes an invalid memory access.
Avoid going through the free code path and return immediately when either the interface type or name are invalid or if the name is duplicate.
Fixes: a0f9d6699605 ("iface: forbid duplicate names on creation")
Reported-by: Christophe Fontaine <cfontain@redhat.com>
> iface: avoid use after free on duplicate name

- modules/ip/datapath/arp_input.c
- modules/ip/datapath/ip_output.c
- modules/ip6/datapath/ip6_output.c
During the processing of an arp message, update the existing nexthop instead of creating a duplicated entry in the nh table.
Closes: https://github.com/DPDK/grout/issues/89
> arp: fix nh lookup

- docs/grout.8.scd
- main/dpdk.c
- main/gr.h
- main/main.c
Some EAL parameters can be useful to profile and/or debug specific issues in DPDK. Add support for the following parameters:
--log-level
--trace
--trace-dir
--trace-bufsz
--trace-mode
The EAL arguments are mapped to grout flags to prevent the users from passing any supported EAL parameter by DPDK. Indeed, grout initialization has specific needs which may get disturbed by some flags. Only expose the ones that are harmless.
> main: add support for debugging eal arguments

- meson.build
- subprojects/ecoli.wrap
The build options have been changed to meson auto features and now default to all enabled if the dependencies are found. Explicitly set editline=enabled to fail if libedit is not installed.
Disable all other features since grout does not need them.
> meson: use latest libecoli release

- modules/ip/datapath/arp_output_reply.c
Given the following configuration:
iface0: 192.168.0.1/32
iface1: 192.168.0.2/24
When an arp_request arrives on iface1 (who has 192.168.0.1?), grout answers with the ip belonging to the interface iface1, so the tip field in the arp message is filled with "192.168.0.2" instead of the requested IP.
Swap the fields SIP and TIP to avoid this: this is safe as the only possible upstream node is "arp_input".
> arp: fix source ip in arp reply

- modules/ip6/datapath/ndp_ns_input.c
With an interface up, we have a race between the local ipv6 assignation and the packet reception.
Check that we have a valid ip6 address before accessing it.
> ip6: fix crash upon interface creation

- main/main.c
-t takes no argument.
While at it, append a \n for error strings.
Fixes: e5fa4943f860 ("wip")
Fixes: d246b537eabd ("main: add support for debugging eal arguments")
> main: fix test mode short option

- README.md
Refer to local content for logo and documentation. This will avoid releases point at the main branch content.
> readme: use relative links

- GNUmakefile
- README.md
- subprojects/dpdk.wrap
- subprojects/packagefiles/log-fix-double-free-on-cleanup.patch
Unfortunately, there is a regression introduced in 24.11. I submitted a fix upstream which is applied locally until it will be merged.
The fix will most likely be backported in the first 24.11 stable Z release.
Link: https://patches.dpdk.org/project/dpdk/patch/20241129161013.704859-2-rjarry@redhat.com/
> dpdk: update to 24.11

- api/gr_net_types.h
- api/meson.build
- api/printf.c
- api/printf_test.c
- modules/infra/cli/port.c
- modules/infra/control/port.c
- modules/infra/datapath/eth_input.c
- modules/infra/datapath/trace.c
- modules/ip/cli/address.c
- modules/ip/cli/icmp.c
- modules/ip/cli/nexthop.c
- modules/ip/cli/route.c
- modules/ip/control/nexthop.c
- modules/ip/control/route.c
- modules/ip6/cli/address.c
- modules/ip6/cli/nexthop.c
- modules/ip6/cli/route.c
- modules/ip6/control/address.c
- modules/ip6/control/nexthop.c
- modules/ip6/control/route.c
- modules/ipip/cli.c
Formatting networking addresses can be tedious and lead to ugly code, especially when dealing with IPv6.
Unfortunately, we cannot use custom printf specifiers since these lead to `-Wformat` warnings. Neither GCC nor clang know of any libc custom printf handlers.
Redefine the builtin `"%p"` pointer printf specifier with a custom function. Leverage the fact that printf supports width specifiers. Use well known widths to associate pointers with specific types. Add short defines to hold these specifiers for clarity:
|  define    |   specifier     |   expected argument type   |
|------------| ----------------| -------------------------   |
|  `ETH_F`     |   `"%2p"`         |   `struct rte_ether_addr *` | 
|  `IP4_F`     |   `"%4p"`         |   `ip4_addr_t *`   |
|  `IP6_F`     |   `"%6p"` …
> treewide: add custom printf specifiers for addresses

- main/gr_log.h
- main/main.c
- modules/infra/api/gr_infra.h
- modules/infra/api/trace.c
- modules/infra/cli/trace.c
- modules/infra/datapath/drop.c
- modules/infra/datapath/eth_output.c
- modules/infra/datapath/gr_trace.h
- modules/infra/datapath/rx.c
Add cli commands in addition to the command line option ( -x ) to enable/disable packet logging.
- set packet logging
- clear packet logging
> infra: add cli to enable/disable packet logging

- modules/infra/cli/iface.c
- modules/infra/control/gr_iface.h
- modules/infra/control/port.c
- modules/infra/control/vlan.c
- modules/ipip/control.c
Add notifications for up/down status, and trigger post-reconfig event for virtual interfaces as well.
This post-reconfig event is required when a 3rd party system will want to get a notification when the VRF associated to an interface is modified.
> Iface internal notifications

- modules/infra/datapath/gr_icmp6.h
- modules/ip6/control/nexthop.c
- modules/ip6/datapath/ndp_na_input.c
- modules/ip6/datapath/ndp_ns_input.c
Expecting that packet data is contiguous is wrong. Plus the current code is not safe against (forged?) truncated packets at the NDP protocol level.
Rework existing helper and avoid pointer arithmetics.
Fixes: fb72a4d6f57c ("ip6: implement dynamic node address discovery")
> ndp: fix icmp6 option parsing

- .github/ISSUE_TEMPLATES/bug_report.yml
- .github/ISSUE_TEMPLATES/config.yml
- .github/ISSUE_TEMPLATES/feature_request.yml
- README.md
Add two templates for new issues: bug report and feature request.
Make it explicit that questions should be sent either to the mailing list or to the slack channel.
Add references to the mailing list and slack channel to the README.
> github: add issue templates

- GNUmakefile
Add a debug target that will force BUILDTYPE=debug and SANITIZE=address.
> mk: add short target to build with debug options

- main/api.c
- main/main.c
If the grout process is launched a second time, then socket api bind() failed and the process unlink socket file before exiting, making the first running process unreachable.
If the grout process crash, it won't remove api socket file, and the next invocation will fail at socket api bind().
Change api_socket_start() to check, if bind() fails, whether there's a listening process behind the scene:
* If there is, exit without removing socket api file
* If there is not, then remove file and resume bind.
> main: improve api socket bind

- modules/infra/control/mempool.c
Fix the following error when building on aarch64:
```
../modules/infra/control/mempool.c: In function ‘gr_pktmbuf_pool_get’:
../modules/infra/control/mempool.c:87:17: error: implicit declaration of function ‘qsort’ [-Wimplicit-function-declaration]
87 |                 qsort(mt, MAX_MEMPOOL_PER_NUMA, sizeof(*mt), mt_sort);
|                 ^~~~~
```
Add the missing include of stdlib.h
Fixes: 189ae9d7a5b9 ("infra: add wrapper to create mempools")
> mempool: fix build error on aarch64

- modules/infra/control/gr_nh_control.h
- modules/infra/control/nexthop.c
- modules/infra/datapath/loop_input.c
- modules/ip/control/nexthop.c
- modules/ip/datapath/icmp_input.c
- modules/ip6/control/address.c
- modules/ip6/control/gr_ip6_control.h
- modules/ip6/control/nexthop.c
- modules/ip6/control/route.c
- modules/ip6/datapath/icmp6_output.c
- modules/ip6/datapath/ip6_input.c
- modules/ip6/datapath/ndp_na_input.c
- modules/ip6/datapath/ndp_ns_input.c
- smoke/ip6_forward_test.sh
- smoke/ip6_same_peer_test.sh
Scoped link local addresses implementation
Still has some issues:
```
grout# add ip6 route ::0/0 via fe80::4e77:6dff:fe7d:1cc7
error: command failed: No route to host
```
This link local address doesn't exist in the FIB, but fe80:100::4e77:6dff:fe7d:1cc7 and fe80:300::4e77:6dff:fe7d:1cc7 are present internally.
```
grout# add ip6 route ::0/0 via fe80:100::4e77:6dff:fe7d:1cc7
grout# show ip6 route
VRF  DESTINATION                    NEXT_HOP
0    fe80::209:c000:17e:f6b/128     fe80::209:c000:17e:f6b
0    fe80::4e77:6dff:fe7d:1cc7/128  fe80::4e77:6dff:fe7d:1cc7
0    fe80::1:1/128                  fe80::1:1
0    fe80::4e77:6dff:fe7d:1cc7/128  fe80::4e77:6dff:fe7d:1cc7
0    fe80::90e2:ba00:314:2f8c/128   fe80::90e2:ba00:314:2f8c
0    ::/0                           fe80::4e77:6dff:fe7d:1cc7 …
```
> Ip6 scoped linklocal

- modules/ip/control/address.c
memset triggers a use after free when an interface is removed. Use the proper gr_vec_free to release the associated memory instead.
Fixes: 9dedabb ("address: use variable length hoplist")
> ip: fix use after free

- modules/infra/api/meson.build
"gr_nexthop.h" is missing, preventing the proper build of management applications.
Fixes: fa0019c ("nexthop: factorize api objects between v4 and v6")
> sdk: add missing header

- .github/workflows/check.yml
When the source branch of a pull request (e.g. rjarry/grout:foobar) is not up to date with the target branch (e.g. DPDK/grout:main), the rebase command does nonsense.
```
~# git rebase -x "git --no-pager log --oneline -1 && make lint" \
"46b14b01748c7a8ea31bce76e3e100f0432ff20f"
Rebasing (1/14)
Committer identity unknown
...
fatal: unable to auto-detect email address (got 'root@a6b854a16cce.(none)')
```
In that case 46b14b01748c7a8ea31bce76e3e100f0432ff20f is a merge commit id (e.g. `refs/pulls/$num/merge`) generated automatically by GitHub when the pull request source branch has diverged from the target main branch.
Unfortunately, `actions/checkout` does use `${{ github.ref }}` to determine the checked out revision. Depending on the context in which the jobs are executed, `${{ github.ref …
> ci: fix rebase error when source branch is not up to date with target

- smoke/ip6_forward_test.sh
- smoke/ip6_rs_ra_test.sh
- smoke/ip6_same_peer_test.sh
- smoke/ip_forward_test.sh
- smoke/ipip_encap_test.sh
- smoke/vlan_forward_test.sh
- smoke/vrf_forward_test.sh
We have tests that use publicly routable addresses (16.0.0.0/8). By default, ping and traceroute will try to resolve any IP address to a hostname via the configured name server method for getnameinfo(3).
We certainly don't want that to happen as these programs will at best give up after the default timeout, or at worse print a garbage host name.
Force numeric output only with the -n flag which is supported by all ping, traceroute and ndisc6.
This has the side benefit of making the smoke tests a lot faster:
before:  ip_forward_test.sh ... OK (01m08s)
after:   ip_forward_test.sh ... OK (00m06s)
Fixes: 75286b77c3df ("ip: ensure no nexthop is created with invalid iface id")
> smoke: prevent any address to name resolution

- modules/infra/control/nexthop.c
nexthop_lookup uses nh_pool_iter() with nh_pool_iter_cb to walk through all nexthops that are referenced by a route. Nexthops are only created and modified by the control thread but nexthop_lookup can be called by data plane workers as well (e.g. when receiving ARP and NDP packets).
There can be a race condition where a nexthop was allocated by the control thread, the address field has been set but the nexthop is not yet referenced by a route when a data plane thread calls nexthop_lookup().
Adjust the assert condition to ignore the address field contents when called from a data path thread.
Fixes: 7d6a8d6296d2 ("ip: split rib and fib")
> infra: fix bogus assert in nexthop_lookup

- modules/infra/control/vlan.c
Update vlan MTU and state.
Closes #94
> vlan fixes

- docs/grout.8.md
- main/dpdk.c
- main/gr.h
- main/grout.default
- main/main.c
Relying on environment variables to determine whether logs should be redirected to syslog/journald is unreliable.
For example, desktop environments may be started as systemd transient services with systemd-cat and INVOCATION_ID may be present in the environment variables without the user/developer having any control over it.
Instead of trying to guess in which context grout is executed, add a new --syslog flag that will explicitly redirect logs to syslog.
> main: add flag to redirect to syslog

- modules/ip6/api/gr_ip6.h
- modules/ip6/cli/icmp6.c
- modules/ip6/control/icmp6.c
Add a new optional parameter on ping6/traceroute6 api: source interface.
It allows correct route selection when ip6 destination address is link-local.
If ip6 destination address is not link-local, this new parameter will be ignored.
> ip6: add source interface on ping6 command.

- modules/ip/control/address.c
- modules/ip6/control/address.c
- smoke/ip6_add_del_test.sh
- smoke/ip_add_del_test.sh
ip and ip6 address deletion never worked, and returned EBUSY.
Only check that the nexthop isn't referenced by another entity instead of checking the flags.
> ip/ip6: fix ip(6) address deletion

- modules/ip6/datapath/ip6_local.c
rte_pktmbuf_read() needs a buffer length and a pointer to the buffer. _ext is an array of uint8_t of size 4. sizeof(&_ext) returns the size of a pointer (8 bytes). This means that rte_pktmbuf_read() will potentially overflow on the stack if the packet is not contiguous.
Fix the call to rte_pktmbuf_read() by passing sizeof(_ext) and _ext without prefixing them with &.
Also, rte_ipv6_get_next_ext only reads 2 bytes at most from the ext parameter. Change the size of _ext to be a 2 bytes array.
If reading from the mbuf fails, stop processing immediately and drop the packet with an explicit ip6_input_local_error stat.
Fixes: 520047d56e4c ("ip6: fix IPv6 extension header parsing")
> ip6_local: fix extension header parsing

- README.md
- modules/infra/cli/iface.c
- smoke/_init.sh
- smoke/config_test.sh
Instead of using 'show interface all' to list all interfaces, we can just type 'show interface'.
Update doc and tests.
> infra: simplify show interface cli

- modules/infra/api/gr_infra.h
- modules/infra/api/gr_nexthop.h
- modules/infra/cli/gr_cli_iface.h
- modules/infra/cli/iface.c
- modules/infra/control/gr_iface.h
- modules/infra/control/gr_port.h
- modules/infra/control/iface.c
- modules/infra/control/port.c
- modules/infra/control/vlan.c
- modules/infra/control/worker_test.c
- modules/infra/datapath/gr_icmp6.h
- modules/ip/datapath/gr_ip4_datapath.h
- modules/ip/datapath/ip_output.c
- modules/ip6/datapath/gr_ip6_datapath.h
- modules/ip6/datapath/ip6_output.c
- modules/ipip/control.c
- modules/ipip/gr_ipip.h
Make our lives a bit easier when debugging, switching from opaque flags value to an explicit enum.
Instead of 
```
(gdb) p nh->flags
$7 = 178
```
We have now:
```
(gdb) p nh->flags
$7 = (GR_NH_F_REACHABLE | GR_NH_F_STATIC | GR_NH_F_LOCAL | GR_NH_F_LINK)
```
> Replace defines with enums

- main/dpdk.c
When running grout in a VM and hotplugging a port, the IOVA mode used is always VA, which leads to the impossibility to bind the port.
ERR: PCI_BUS:   Expecting 'PA' IOVA mode but current mode is 'VA', not initializing
Check if 'noiommu' is enabled, and sets iovamode to "PA".
Suggested-by: David Marchand <david.marchand@redhat.com>
> infra: set iova mode

- modules/infra/api/gr_infra.h
- modules/infra/api/gr_nexthop.h
- modules/infra/control/gr_iface.h
- modules/infra/control/iface.c
- modules/infra/control/nexthop.c
- modules/infra/datapath/gr_icmp6.h
- modules/ip/datapath/ip_output.c
- modules/ip6/datapath/ip6_output.c
- update enum types
This increases minimum gcc version to gcc 13.
> c2x: enum types

- .github/workflows/check.yml
- devtools/cross/aarch64.ini
- meson.build
- modules/l4/l4_input_local.c
Add multiple jobs to ensure that the compilation works on gcc 11, 14 and clang 13 and 18.
Enable ccache to get results faster.
> ci: add clang and older gcc checks

- .github/workflows/publish.yml
- main/main.c
This reverts commit 719935e775fcdb1649e0b2f17814c547d2725426, using quay.io instead of github to host container images.
Container is available at:
quay.io/grout/grout
Available tags are:
- edge: latest build, including all merged changes
- latest: latest stable release
- v0.X: tagged versions
> quay: build and publish container

- modules/infra/datapath/loop_output.c
- modules/ip/datapath/gr_ip4_datapath.h
- modules/ip/datapath/ip_output.c
- modules/ip6/datapath/gr_ip6_datapath.h
- modules/ip6/datapath/ip6_output.c
- modules/ipip/datapath_out.c
Allow registering dynamic next nodes after ip_output and ip6_output based on the nexthop type.
This will allow redirecting packets to different nodes for special processing, such as SRv6.
> ip,ip6: handle nexthop types

- Containerfile
Use ubi-micro to reduce container image size.
Yet, we can't run dnf directly, so switch to multistage build to install all dependencies in a tmp rootfs.
> container: multistage build

- modules/infra/datapath/main_loop.c
- modules/ip/control/route.c
- modules/ip6/control/route.c
- smoke/ip6_add_del_test.sh
- smoke/ip_add_del_test.sh
- Simple fix on interface creation.
- Cleanup ip6 rib when an IPv6 address is deleted
> misc fixes: ip6

- meson.build
- modules/ip/datapath/ip_input.c
- modules/ip/datapath/meson.build
This patch introduces unit tests to validate the correctness of the IPv4 header processing in the ip_process_input function. The tests check for key properties such as IP version, checksum calculation, packet length, etc ...
> ip: add unit tests to validate ip header

- .github/workflows/check.yml
- .github/workflows/publish.yml
Since we are limiting the git fetched ref prior to the automated merge commit associated with every pull request, the latest tag is never fetched.
Force fetch all tags every time (except the "edge" tag which is a moving target).
> github: force fetch tags

- modules/ip/datapath/arp_output_request.c
- modules/ip6/datapath/ndp_ns_output.c
After a nexthop expired, and when the peer doesn't respond to unicast probes, grout never switched back to broadcast (ip) or multicast (ip6) probes.
Instead of checking on the ucast probe counter, check the bcast probe counter.
> nexthop: fix mcast/bcast solicit

- meson.build
When building from outside of grout repository for downstream packaging, we cannot rely on git to get the version from the latest tag.
Allow building with a GROUT_VERSION variable that will be used in meson.build.
> meson: allow forcing version via environment variable

- modules/infra/control/nexthop.c
- modules/ip/control/nexthop.c
- modules/ip6/control/nexthop.c
After a fixed period of time (20 minutes), grout will mark non-static nexthops that were resolved earlier (with ARP or NDP) as STALE and will try to probe them to refresh their mac addresses.
After 6 probes have been sent (3 unicast using the previously known mac address of the nexthop, and 3 broadcast/multicast) without any reply from the nexthop, it is marked as FAILED.
After 1 minute in the FAILED state, it is "freed" using the callback specified in the nexthop_ops per family (at the moment, only IPv4 and IPv6).
The current callbacks are rib4_cleanup and rib6_cleanup which are very aggressive. They effectively delete everything related to the nexthop. Including any local address, routes, etc.
Replace these callbacks with simpler ones which only delete /32 and /128 routes and decrement …
> nexthop: fix disappearing addresses and routes after expiration

- cli/gr_table.h
- cli/meson.build
- meson.build
Since libsmartcols 2.41, scols_line_sprintf is available and does not need to be implemented by grout. Add the required meson code to avoid building our local version when the symbol is available in the library.
Link: https://github.com/util-linux/util-linux/commit/f0d0817c37931b504a7
> cli: use scols_line_sprintf if available

- modules/infra/control/graph.c
When no hugepages are available on numa 0, the rte_hash initialization fails:
```
INFO: GROUT: dpdk_init: EAL arguments: -l 3 -a 0000:00:00.0 --in-memory
NOTICE: EAL: 8000 hugepages of size 2097152 reserved, but no mounted hugetlbfs found for that size
INFO: GROUT: dpdk_init: running control plane on CPU 3
INFO: GROUT: dpdk_init: datapath workers allowed on CPUs 5,51,53
ERR: EAL: set_mempolicy failed: Invalid argument
ERR: EAL: set_mempolicy failed: Invalid argument
ERR: RING: Cannot reserve memory
ERR: HASH: memory allocation failed
EMERG: GROUT: graph_init: rte_hash_create: Cannot allocate memory
```
This happens because the socket_id field is left to its "default" value which happens to be 0. Replace it with SOCKET_ID_ANY which will cause the allocator to use whatever is available. …
> graph: fix hash init when no memory is available on numa 0

- modules/infra/api/gr_nexthop.h
These values were taken from Linux. We only need them for display purposes in the CLI.
Link: https://github.com/torvalds/linux/blob/v6.14/include/uapi/linux/rtnetlink.h#L298-L315
> nexthop: add more route origin values

- modules/ip/control/address.c
- modules/ip6/control/address.c
When an IP address is removed, the RIB cleanup process (rib4/6_cleanup) resets associated nexthop memory before the addr del event is sent. As a result, the event includes a nexthop structure with all fields set to zero, even though a valid nexthop was previously in use.
To reproduce:
grcli show events
> addr add: iface[1] 9.6.6.7
> route del: 9.6.6.7/24 via 9.6.6.7 origin link
> nh del: iface 1 vrf 0 9.6.6.7 d2:f0:0c:bc:a4:10
> addr del: iface[0] 0x5d279f4eb1ac
Or from another instance:
grout# add ip address 9.6.6.7/24 iface p4
grout# del ip address 9.6.6.7/24 iface p4
Fix this by emitting the addr del event before the nexthop is cleaned up, ensuring the event still carries valid nexthop information.
> modules/ip[6]: fix uninitialized nexthop in "addr del" event

- modules/infra/control/port.c
At startup, we pass -a 0000:00:00.0 to rte_eal_init() to disable automatic PCI probing. However, this only affects the PCI bus devices. Other buses (e.g. FSMLC) are not affected by this argument and are always probed in rte_eal_init().
When configuring a port with such a device, we get an error from the API saying that the port is already attached to another interface:
grout# add interface port dpni2 devargs fslmc:dpni.2
error: File exists
Instead of iterating over the DPDK probed devices, look at grout ports to determine whether a port matching this devargs value is already configured.
If we cannot find one, check if the device has already been probed and only probe it if it was not.
> port: allow attaching already probed devices

- modules/infra/api/gr_infra.h
- modules/infra/cli/port.c
- modules/infra/control/port.c
Ports with higher speeds (100gb/s and 400gb/s) are not represented in the API. The field is only a 16bit wide integer. These values are truncated.
Change the field to use 32 bits as it is in the DPDK API.
Fixes: 5a25e184cb1d ("port: expose link_speed to the api")
> port: avoid truncating link speed values above 64gb/s

- modules/infra/control/port.c
- modules/infra/control/vlan.c
- modules/ipip/control.c
There is no need to copy individual fields. Use the base structures to copy common fields from the internal and public API messages.
Fixes: c5f94a9386ae ("iface: reuse public structures")
> iface: use base structures for copying to api

- modules/infra/control/port.c
The dpaa2 devices do not support close/re-open with the current DPDK. Let's work around this limitation for the time being.
Fix:
```
grout# add interface port dpni.2 devargs fslmc:dpni.2 up mode l3
Created interface 1
grout# del interface dpni.2
grout# add interface port dpni.2 devargs fslmc:dpni.2 up mode l3
error: command failed: Identifier removed
```
Fixes: 9ca93361aea1 ("port: allow attaching already probed device")
> dpaa2: do not close devices

- cli/ec_node_devargs.c
- docs/grcli.1.md
Add support for parsing and adding to the autocomplete the contents of the fslmc bus (for example for a LX2160 QorIQ CPU).
Example:
```
grout# add interface port dpni.2 devargs <?>
fslmc:dpni.2       net_null           net_tap            net_tun
net_vhost          net_virtio_user
grout# add interface port dpni.2 devargs f<tab>
grout# add interface port dpni.2 devargs fslmc:dpni.2
```
The bus cases (PCI, fslmc, vdev) have not been redesigned.
> cli: autocomplete support on fslmc CPUs (QorIQ)

- modules/infra/control/graph.c
At initialization, grout modules are ordered by their init_prio value. The default value is 0 unless overridden. At the moment, no module specifies its init_prio so they are all "equal". The order in which modules are initialized is therefore decided at link time and is non-deterministic.
Since commit a610da9bdaa9 ("infra: add generic ctrlplane to dataplane node"), gr_control_input_register_handler can be called by any module to register a children node after "control_input". Unfortunately, this function needs the "control_input" node to have been registered first which is only done when the "graph" module is initialized.
Depending on the link time ordering of `__attribute__((constructor))` functions, we may see grout crash on startup as follows:
DEBUG: GROUT: modules_init: srv6_headend …
> graph: enforce early node register

- api/gr_string.h
- api/string.c
- main/main.c
- modules/infra/control/iface.c
Change explicit setlocale(LC_CTYPE, "C.UTF-8") to setlocale(LC_ALL, "") to initialize the wide char encoding to whatever locale is enabled in the environment.
Rename utf8_check to charset_check to avoid confusion since the encoding may now be a non-UTF-8 charset.
> main: use locale from environment

- cli/main.c
setlocale(LC_CTYPE, "C.UTF-8") has been replaced setlocale(LC_ALL, "") for grout, but not for grcli. Let's fix it.
Fixes: 66e067f91e57 ("main: use locale from environment")
> cli: use locale from environment

- modules/infra/datapath/gr_icmp6.h
- modules/ip6/control/nexthop.c
- modules/ip6/datapath/meson.build
- modules/ip6/datapath/ndp_na_input.c
- modules/ip6/datapath/ndp_ns_input.c
According to https://datatracker.ietf.org/doc/html/rfc4861#section-4.6,  neighbor discovery packets with option length 0 is not dropped, currently it is not so. Added fix for that along with unit tests for NDP NA input process. 
Fixes: https://github.com/DPDK/grout/issues/115
> Discard NDP packets containing null length option

- modules/infra/control/gr_nh_control.h
- modules/infra/control/iface.c
- modules/infra/control/nexthop.c
When an interface is removed, associated next hop remains with an unknown interface id:
grout# show ip6 nexthop
VRF  IP                         MAC                IFACE    QUEUE  AGE   STATE
0    fe80::d2f0:cff:feba:a411   d2:f0:0c:ba:a4:11  gmztio1  0      -     reachable static local link
0    fe80::d2f0:cff:feba:a412   d2:f0:0c:ba:a4:12  gmztio2  0      -     reachable static local link
0    fd00:ba4:1::1              d2:f0:0c:ba:a4:11  gmztio1  0      -     reachable static local link
0    fd00:ba4:2::1              d2:f0:0c:ba:a4:12  gmztio2  0      -     reachable static local link
0    fe80::d0ad:caff:feca:a401  d2:ad:ca:ca:a4:01  gmztio1  0      3     reachable
0    fe80::d0ad:caff:feca:a401  d2:ad:ca:ca:a4:01  gmztio2  0      3     reachable
--> remove interfaces gmztio1 and …
> nh: cleanup on interface deletion

- modules/infra/api/stats.c
- modules/infra/datapath/main_loop.c
Since commit 480f653f57e2 ("worker: keep threads running all the time"), workers are no longer destroyed when not assigned any interfaces.
Make sure to wake up sleeping workers so that they reset their own statistics.
Fixes: 480f653f57e2 ("worker: keep threads running all the time")
> stats: fix reset when workers are sleeping

- modules/infra/control/port.c
- smoke/ip_forward_test.sh
In order to support receiving packets larger than 2048 bytes, we need to enable multi-segment rx and tx offload in the drivers.
Enable RTE_ETH_RX_OFFLOAD_SCATTER and RTE_ETH_TX_OFFLOAD_MULTI_SEGS in the requested offload flags when configuring DPDK ports.
Update the basic IP forward test to check we are indeed receiving 5000 bytes packets with a configured MTU of 9000 bytes.
Suggested-by: David Marchand <david.marchand@redhat.com>
> rx,tx: enable multi segment to support higher mtu

- modules/infra/api/gr_infra.h
- modules/infra/api/stats.c
- modules/infra/cli/iface.c
- modules/infra/control/gr_iface.h
- modules/infra/control/iface.c
- modules/infra/datapath/eth_input.c
- modules/infra/datapath/eth_output.c
- modules/infra/datapath/l1_xconnect.c
- modules/ipip/datapath_in.c
- modules/ipip/datapath_out.c
- Implement per interface statistics
- Export them via DPDK telemetry socket
- Export them via grcli with `show interface stats`
- Implement clear stats with `clear stats`
> infra: export interface statistics through DPDK telemetry socket

- .github/workflows/review.yml
Enable automated AI code reviews on pull requests using OpenAI API.
Link: https://github.com/anc95/ChatGPT-CodeReview
Link: https://platform.openai.com/docs/api-reference/runs/createRun
> github: add automated ai code review

- frr/if_grout.c
- frr/if_grout.h
- frr/rt_grout.c
- frr/rt_grout.h
- frr/zebra_dplane_grout.c
- modules/infra/api/gr_nexthop.h
- modules/infra/api/nexthop.c
- modules/infra/cli/events.c
- modules/infra/cli/nexthop.c
- modules/infra/control/nexthop.c
- modules/ip/api/dnat44.c
- modules/ip/api/gr_ip4.h
- modules/ip/cli/route.c
- modules/ip/control/address.c
- modules/ip/control/gr_ip4_control.h
- modules/ip/control/nexthop.c
- modules/ip/control/route.c
- modules/ip6/api/gr_ip6.h
- modules/ip6/cli/route.c
- modules/ip6/control/address.c
- modules/ip6/control/gr_ip6_control.h
- modules/ip6/control/nexthop.c
- modules/ip6/control/route.c
- modules/srv6/control/localsid.c
- modules/srv6/control/route.c
- smoke/nexthop_ageing_test.sh
- subprojects/packagefiles/frr/meson-add-dependency-definition.patch
Support nexthop id sync with frr plugin
> Frr nexthop

- subprojects/frr.wrap
It's required for SRv6 encap in staticd IPv4 routes. When 10.4 will be released, we should upgrade it again. (end of week maybe)
> subprojects/frr: bump to 10.4-rc1

- modules/infra/control/nexthop.c
When 3 unicast ARP/NDP and 3 {broad,multi}cast probes have failed to get a response, the nexthop is marked as "failed" and is "deleted" after lifetime_unreachable_sec (60 seconds by default).
This deletion is rather aggressive and completely removes all routes that point to this failed nexthop. This may have unwanted side effects when running for a long time in production.
Keep the nexthop alive and leave all routing tables alone.
> nexthop: avoid nuking routing tables after 6 arp/ndp failures

- modules/infra/api/nexthop.c
- modules/ip6/control/route.c
Remove the check for GR_NH_F_LOCAL and GR_NH_F_GATEWAY. Only make sure that local addresses (GR_NH_F_LOCAL | GR_NH_F_STATIC) and non L3 nexthops cannot be deleted.
> nexthop: allow deleting regardless of flags

- .github/workflows/check.yml
- modules/srv6/api/gr_srv6.h
- modules/srv6/cli/localsid.c
- modules/srv6/control/route.c
- modules/srv6/datapath/srv6_local.c
- **github: check individual commits for a single matrix job**
- **srv6: improve behavior parsing and formatting**
- **srv6: use {rib4,rib6}_iter instead of checking all nexthops**
- **srv6: cleanup tunsrc code**
> srv6 cleanup
