DPDK/grout

modules/infra/datapath/eth_input.c
modules/infra/datapath/gr_eth_input.h
modules/ip/datapath/arp_input.c
modules/ip/datapath/gr_ip4_datapath.h
modules/ip/datapath/icmp_input.c
modules/ip/datapath/ip_input.c
modules/ip/datapath/ip_local.c
modules/ipip/datapath_in.c

Reduce boiler plate code when we add new ether proto or ip proto.
- gr_eth_input_add_type
- ip_input_local_add_proto

api: add node with name instead of edge

---

modules/infra/control/gr_iface.h
modules/infra/control/iface.c
modules/infra/control/port.c
modules/infra/control/worker_test.c

Closes: https://github.com/rjarry/brouter/issues/28

infra: implement interface events notifications

---

modules/infra/control/port.c

Some DPDK drivers return a positive from with rte_eth_dev_close(). This leads to incomplete cleanup and inconsistent state.
Fix the code so that when returning from iface_port_fini(), all resources have been properly cleaned up.
Reported-by: Christophe Fontaine <cfontain@redhat.com>

port: ensure complete cleanup on port deletion

---

modules/infra/api/gr_infra.h
modules/infra/cli/port.c
modules/infra/control/port.c

Add the driver name to the command "show interface"
grcli show interface name <ifname>
driver:  net_ixgbe

infra/port: display driver name

---

modules/ip/datapath/ip_forward_error.c

Fix an error when receiving multicast IP packets without any IP address configured on an interface.

infra: check ip availability

---

api/gr_bitops.h
api/gr_net_types.h
cli/ecoli.c
cli/gr_cli.h
meson.build
modules/infra/api/gr_infra.h
modules/infra/cli/port.c
modules/infra/cli/vlan.c
modules/infra/control/gr_iface.h
modules/infra/control/gr_port.h
modules/infra/control/iface.c
modules/infra/control/port.c
modules/infra/control/vlan.c
modules/infra/datapath/eth_input.c
modules/infra/datapath/eth_output.c
modules/infra/datapath/trace.c
modules/ip/api/gr_ip4.h
modules/ip/cli/nexthop.c
modules/ip/cli/route.c
modules/ip/control/nexthop.c
modules/ip/control/route.c
modules/ip/datapath/arp_input.c
modules/ip/datapath/arp_output_reply.c
modules/ip/datapath/arp_output_request.c
modules/ip/datapath/ip_forward.c
modules/ip/datapath/ip_input.c
modules/ip/datapath/ip_output.c

- wrappers to call rte_eth_dev_mac_addr_[add|remove]
- Add API to filter multicast addresses on ports
resolves #27

infra/port: implement multicast l2 filtering

---

modules/infra/control/control_output.c
modules/infra/control/meson.build
modules/infra/datapath/control_output.c
modules/infra/datapath/gr_control_output.h
modules/infra/datapath/meson.build
modules/infra/datapath/trace.c
modules/ip/api/gr_ip4.h
modules/ip/cli/icmp.c
modules/ip/cli/meson.build
modules/ip/control/icmp.c
modules/ip/control/meson.build
modules/ip/datapath/gr_ip4_datapath.h
modules/ip/datapath/icmp_input.c
modules/ip/datapath/icmp_local_send.c
modules/ip/datapath/ip_error.c
modules/ip/datapath/meson.build
modules/ipip/datapath_out.c
smoke/_init.sh
smoke/ip_builtin_icmp_test.sh
subprojects/dpdk.wrap
subprojects/packagefiles/dpdk/net-add-more-icmp-types-and-code.patch

`traceroute` relies on ICMP, and not UDP.

add ping v4 & traceroute v4 (ICMP) utilities

---

debian/rules
docs/meson.build
meson.build
meson_options.txt
rpm/grout.spec

Avoid the dependencies when manual and tests are disabled.

meson: scdoc and cmocka are optionals

---

main/api.c

The docstring of event_base_foreach_event() states explicitly that modifying events in the callback function is unsafe and will cause crashes.
event_free_finalize tries to acquire a lock that is already held when the callback is called. Leading to a deadlock:
```
(gdb) bt
...
#3  ___pthread_mutex_lock (mutex=0x504000001550) at pthread_mutex_lock.c:93
#4  0x00007f3f211b8485 in event_finalize_impl_ (flags=65536, ev=0x50c000005200, cb=0x4031ba <finalize_fd>)
#5  0x00000000004042ed in close_connections (ev=0x50c000005200) at main/api.c:174
...
#10 0x00007f3f211b263a in event_base_foreach_event (base=0x517000006d00, fn=0x40429f <close_connections>, arg=0x0)
#11 0x0000000000404a3a in api_socket_stop () at main/api.c:253
#12 0x00000000004072aa in main (argc=4, argv=0x7ffcc575d898) at …
```

api: fix deadlock on shutdown when clients are connected

---

.github/workflows/check.yml
devtools/cross/aarch64.ini

Enable cross-compilation for ARM64.

github: enable cross build for arm64

---

modules/infra/datapath/eth_input.c
modules/infra/datapath/loop_input.c
modules/ip6/datapath/ip6_local.c

Here is a series trying to fix issues described in #114.
One small concern is wrt the packet tracing feature, where should the data offset be pointing at?

Fix calls to rte_pktmbuf_adj().

---

modules/infra/control/gr_nh_control.h
modules/ip/control/address.c
modules/ip6/control/address.c

Replace the hard coded maximum size for the hoplist structure with a dynamic vector.

address: use variable length hoplist

---

README.md
main/grout.init
modules/infra/cli/port.c
modules/infra/datapath/eth_output.c
modules/infra/datapath/tx.c

Small rework:
- move packet logging in tx_output instead of eth_output
- move qmap config to "set worker map".

Misc fixes

---

cli/ecoli.c
cli/gr_cli.h
modules/ip/cli/address.c
modules/ip/cli/icmp.c
modules/ip/cli/nexthop.c
modules/ip/cli/route.c
modules/ip6/cli/address.c
modules/ip6/cli/icmp6.c
modules/ip6/cli/nexthop.c
modules/ip6/cli/route.c
modules/ipip/cli.c

Add helpers, only for cli:
arg_ip4
arg_ip6
arg_ip4_net
arg_ip6_net
And use them on ip/ip6 cli modules.

cli: add arg_ip* helpers

---

.github/workflows/check.yml

Add clang 15 on ubuntu 22.04 to the build matrix.

ci: add clang 15

---

modules/ip/datapath/ip_input.c

The current code assumes that the hardware performs the following checks:
- The packet length is sufficient to accommodate the minimum length of the IP header.
- The IP version is set to 4.
- The IP header length field is large enough to accommodate the minimum legal IP datagram length.
However, these assumptions are incorrect, at least with the tap driver. The following packets can be created using Scapy:
> p_badversion = Ether(dst='f0:0d:ac:dc:00:00', src='ba:d0:ca:ca:00:00')/IP(version=5, src='172.16.0.2', dst='172.16.1.2')
> p_badihl = Ether(dst='f0:0d:ac:dc:00:00', src='ba:d0:ca:ca:00:00')/IP(src='172.16.0.2', dst='172.16.1.2', ihl=3)
> p_truncated = Ether(dst='f0:0d:ac:dc:00:00', src='ba:d0:ca:ca:00:00')/IP(src='172.16.0.2', dst='172.16.1.2')[:14+10]
If the correct routes are …

ip: enhance ip header validation

---

modules/ip6/datapath/ip6_input.c
modules/ip6/datapath/meson.build

Ip6 header check

---

modules/infra/api/gr_nexthop.h
modules/infra/control/iface.c

Few small enhancement to support FRR.

Frr integration

---

smoke/nexthop_ageing_test.sh

Need to run buildroot test on gitlab. Else failed because of timeout issue.

smoke: make nexthop ageing test more robust on slow machines

---

.github/workflows/check.yml
.github/workflows/publish.yml
GNUmakefile
README.md
api/gr_api.h
api/gr_api_client_impl.h
cli/complete.c
cli/ec_node_dyn.c
cli/gr_cli.h
cli/main.c
debian/control
docs/grout.8.md
main/api.c
main/gr_config.h
main/main.c
meson.build
rpm/grout.spec
smoke/_init.sh

RFC about socket permission for frr

Socket group
